apps_1/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', index, name='index'),
]

apps_3/urls.py
from django.conf.urls import url
from .views import index, add_forum

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_forum', add_forum, name='add_forum'),
]

bukapacil/urls.py
from django.conf.urls import url, include
from django.views.generic.base import RedirectView
from django.contrib import admin
import apps_1.urls as apps_1
import apps_2.urls as apps_2
import apps_3.urls as apps_3
import apps_4.urls as apps_4

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^apps-1/', include(apps_1, namespace='apps-1')),
    url(r'^apps-2/', include(apps_2, namespace='apps-2')),
    url(r'^apps-3/', include(apps_3, namespace='apps-3')),
	url(r'^apps-4/', include(apps_4, namespace='apps-4')),
	url(r'^$', RedirectView.as_view(url='/apps-1/', permanent=True)),
]

apps_3/models.py
from django.db import models

# Create your models here.
class Forums(models.Model):
   lowongan = models.TextField()
   created_date = models.DateTimeField(auto_now_add=True)

apps_3/forms.py
from django import forms

class Forum_Lowongan(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    lowongan_attrs = {
        'type': 'text',
        'cols': 139,
        'rows': 4,
        'class': 'todo-form-textarea',
        'placeholder':'Forum Discussion...'
    }

    lowongan = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=lowongan_attrs))

apps_3/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import Forum_Lowongan
from .models import Forums


# Create your views here.
response = {'author':'Muhammad Jihad Rinaldi', 'requirement':["Web Developer", "Mobile Developer", "Software Engineer"]}
def index(request):


    forum_list = Forums.objects.all()
    forum_latest = forum_list[::-1]
    page = request.GET.get('page', 1)
    paginator = Paginator(forum_latest, 5)
    try:
        forum = paginator.page(page)
    except PageNotAnInteger:
        forum = paginator.page(1)
    except EmptyPage:
        forum = paginator.page(paginator.num_pages)
    response['forum'] = forum
    response['forum_lowongan'] = Forum_Lowongan
    html = 'apps_forums/forum.html'

    return render(request, html, response)

def add_forum(request):
    form = Forum_Lowongan(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['lowongan'] = request.POST['lowongan']
        forum = Forums(lowongan=response['lowongan'])
        forum.save()
        return HttpResponseRedirect('/apps-3/')
    else:
        return HttpResponseRedirect('/forum/')

def paginate_page(page, data_list):
    paginator = Paginator(data_list,10)
    try:
        data = paginator.page(page)
    except PageNotAnInteger:
        data = paginator.page(1)
    except EmptyPage:
        data = paginator.page(paginator.num_pages)

    # index of current page
    index = data.number - 1
    # maximum page
    max_index = len(paginator.page_range)
    # range of 10, slicing
    start_index = index if index >= 3 else 0
    end_index = 3 if index < max_index - 3 else max_index
    page_range = list(paginator.page_range)[start_index:end_index]
    paginate_data = {'data': data, 'page_range': page_range}
    return paginate_data

apps_3/templates/apps_forums/forum.html
{% extends "apps_forums/layout/base.html" %}
{% block content %}
<h1><strong><center>Forum Magang Buka Pacil</center><strong></h1>

<div class="" style="  padding-bottom: 50px;">
  <img src="https://d30y9cdsu7xlg0.cloudfront.net/png/372818-200.png" alt="" class="pull-left">
  <br>
  <h2 style="color:red"><strong>Buka Pacil Membuka Peluang Magang Untuk:</strong></h2>
  {% for ii in requirement %}
   <li style="color:blue"><strong>{{ forloop.counter }}. {{ii}}</strong>
     {% endfor %}
</div>
<hr>
<br>

<section name="my-list" id="my-list">
    <div class="container">
        <h2 class="my-list-title">My List</h2>
        <div class="forum-lowongan">
            {% if forum %} {% for data in forum %}
            <blockquote>
            <p>{{ data.lowongan }}</p>
            </blockquote>
            {% endfor %} {% else %}
            <div class="alert alert-danger text-center">
                Tidak ada data Forum.
            </div>
            {% endif %}


        </div>
    </div>
</section>
<form id="form" method="POST" action="{% url 'apps-3:add_forum' %}">
    <h2><strong><center>POST TO FORUM</center></strong></h2>
    {% csrf_token %} {{ forum_lowongan }}
    <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
    <br>
</form>
<div class="pagination">
    <span class="step-links">
        <ul class="pagination">
        {% if forum.has_previous %}
            <li><a href="?page=1">&laquo; first</a></li>
            <li><a href="?page={{ forum.previous_page_number }}">previous</a></li>
        {% endif %}
        <li><span class="current">Page {{ forum.number }} of {{ forum.paginator.num_pages }}</span></li>
        {% if forum.has_next %}
            <li><a href="?page={{ forum.next_page_number }}">next</a></li>
            <li><a href="?page={{ forum.next_page_number }}">last &raquo;</a></li>
        {% endif %}
        </ul>
    </span>
</div>



{% endblock %}